### PR TITLE
integration: add static code analysis tool;

### PR DESCRIPTION
**Pull request by ss89**
@selm0 what do you think about this?

### CODE REVIEW

**Comment by selm0** [comment]
> @selm0 what do you think about this?

I was thinking about going for this one: https://golangci-lint.run/ it has your tool integrated.
First step, leaving the config untouched as it sounds quite reasonable. What's your opinion?

**Comment by ss89** [comment]
this is going to take some time, it doesn't really state where the errors are, just writes some names...

**Comment by applike-ss** [comment]
i have executed this locally and it spits out way too many false positives for example for "unused" properties in a struct.

That may be the case, when you just look at the struct itsself, but since we embed that given struct in other structs, it is in fact used.

**Comment by ss89** [comment]
@selm0 mind approving this?

**Comment by j4k4** [comment]
i like the idea of integrating static code analysis..  
plz let me have a look at the tools, too :)

**Comment by selm0** [comment]
> i have executed this locally and it spits out way too many false positives for example for "unused" properties in a struct.
> 
> That may be the case, when you just look at the struct itsself, but since we embed that given struct in other structs, it is in fact used.
> 
> EDIT: This is the bug: [golangci/golangci-lint#826](https://github.com/golangci/golangci-lint/issues/826)
> 
> EDIT 2: For the moment i would stay with the staticcheck tool

You could disable `structcheck`.
How does the integration with Goland work with `staticcheck`?

**Comment by ss89** [comment]
in fact i didn't integrate it into my goland, but used the go linter plugin which basically is a wrapper around golangci-lint. That however was putting my macbooks down on its knees because it was too weak to handle it. Or in other words: i wouldn't be able to be productive on the machine ^^

**Comment by ss89** [comment]
@j4k4 i guess you will let me know about your findings and i will wait for you then?

**Comment by j4k4** [comment]
you will be using https://golangci-lint.run/ now?

**Comment by ss89** [comment]
Might try the suggestion of @selm0.

this might also be worth a try: https://blog.jetbrains.com/phpstorm/2020/12/early-access-program-for-qodana-a-new-static-analysis-and-quality-management-tool-by-jetbrains-is-open/

**Comment by ss89** [comment]
@selm0 mind having a look again? would really like to see this one merged soonish. Also please have a very close look (maybe together with @j4k4?) about the funcs i removed. Not sure if these should've been used at a later point or if they are left overs from the past.

**Review by j4k4 — APPROVED** [review]
i like adding the static checks

**Review by selm0 — APPROVED** [review]
Looks good to me.

**Comment by ss89** [comment]
@j4k4 i removed some stuff you added yesterday. Please take a look at my rebase fixes commit if that is ok with you.

**Comment by j4k4** [comment]
all good

**Pull request merged**
