### PR TITLE
validation: log validation failure;

### PR DESCRIPTION
**Pull request by mohamed-justdice**
log the validation `validation.repository_db` err if it returns one.

### CODE REVIEW

**Review by selm0 — APPROVED** [review]
Don't forget to squash your commits

**Comment by j4k4** [comment]
I'm not a fan of this. Why do we need this?  
Usually the caller should decide what should happen on error. I did this error by myself more than once..  
Even logging this as a warning will hurt you if you run into an use case where you don't want to have a warning..

**Comment by selm0** [comment]
> I'm not a fan of this. Why do we need this?
> Usually the caller should decide what should happen on error. I did this error by myself more than once..
> Even logging this as a warning will hurt you if you run into an use case where you don't want to have a warning..

Do you refer to e.g. the logs in db.repository?
It seems to me that you're advocating to remove any logs from gosoline :thinking:

**Comment by j4k4** [comment]
> Do you refer to e.g. the logs in db.repository?
Yes

> It seems to me that you're advocating to remove any logs from gosoline
That's not what I said

But a lot of the gosoline packages is utility code. Especially stuff like validation or repositories..  
The result of fetching or validating a record by itself has no real meaning. How should the validation code know how severe a failing validation is? Only your business layer has the knowledge about that. So the logging should happen there.

**Pull request closed without merging**
